var fromDB = [
    {subject: ':mir', object: 'ontolex#Word', predicate: 'rdf#type' },
    {subject: ':mir', object: ':mir:lemma', predicate: 'ontolex#canonicalForm' },
    // {subject: ':mir', object: ':mir:form1_mir', predicate: 'ontolex#otherForm' },
    {subject: ':mir', object: ':mir:form2_mira', predicate: 'ontolex#otherForm' },
    {subject: ':mir', object: ':mir:form3_miru', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form4_mir', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form5_mirom', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form6_mire', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form7_miry', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form8_mirov', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form9_miram', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form10_miry', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form11_mirami', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form12_mirah', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form13_miru', predicate: 'ontolex#otherForm' },
    // {subject: ':mir', object: ':mir:form14_miru', predicate: 'ontolex#otherForm' },
    {subject: ':mir:lemma', object: '"мир"@ru', predicate: 'ontolex#writtenRep' },
    {subject: ':mir:lemma', object: '"mʲir"@ru-fonipa', predicate: 'ontolex#phoneticRep' },
    {subject: ':mir:lemma', object: 'lexinfo#noun', predicate: 'lexinfo#partOfSpeech' },
    {subject: ':mir:lemma', object: 'lexinfo#inanimate', predicate: 'lexinfo#animacy' },
    {subject: ':mir:lemma', object: 'lexinfo#masculine', predicate: 'lexinfo#gender' },
    // {subject: ':mir:form1_mir', object: '"mʲir"@ru-fonipa', predicate: 'ontolex#phoneticRep' },
    // {subject: ':mir:form1_mir', object: '"мир"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form1_mir', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    // {subject: ':mir:form1_mir', object: 'lexinfo#nominativeCase', predicate: 'lexinfo#case' },
    {subject: ':mir:form2_mira', object: '"ˈmʲirə"@ru-fonipa', predicate: 'ontolex#phoneticRep' },
    {subject: ':mir:form2_mira', object: '"мира"@ru', predicate: 'ontolex#writtenRep' },
    {subject: ':mir:form2_mira', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    {subject: ':mir:form3_miru', object: '"миру"@ru', predicate: 'ontolex#writtenRep' },
    {subject: ':mir:form3_miru', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    {subject: ':mir:form3_miru', object: 'lexinfo#dativeCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form4_mir', object: '"mʲir"@ru-fonipa', predicate: 'ontolex#phoneticRep' },
    // {subject: ':mir:form4_mir', object: '"мир"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form4_mir', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    // {subject: ':mir:form4_mir', object: 'lexinfo#accusativeCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form5_mirom', object: '"ˈmʲirəm"@ru-fonipa', predicate: 'ontolex#phoneticRep' },
    // {subject: ':mir:form5_mirom', object: '"миром"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form5_mirom', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    // {subject: ':mir:form5_mirom', object: 'lexinfo#instrumentalCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form6_mire', object: '"мире"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form6_mire', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    // {subject: ':mir:form7_miry', object: '"миры"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form7_miry', object: 'lexinfo#plural', predicate: 'lexinfo#number' },
    // {subject: ':mir:form7_miry', object: 'lexinfo#nominativeCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form8_mirov', object: '"миров"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form8_mirov', object: 'lexinfo#plural', predicate: 'lexinfo#number' },
    // {subject: ':mir:form8_mirov', object: 'lexinfo#genitiveCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form9_miram', object: '"мирам"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form9_miram', object: 'lexinfo#plural', predicate: 'lexinfo#number' },
    // {subject: ':mir:form9_miram', object: 'lexinfo#dativeCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form10_miry', object: '"миры"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form10_miry', object: 'lexinfo#plural', predicate: 'lexinfo#number' },
    // {subject: ':mir:form10_miry', object: 'lexinfo#accusativeCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form11_mirami', object: '"мирами"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form11_mirami', object: 'lexinfo#plural', predicate: 'lexinfo#number' },
    // {subject: ':mir:form11_mirami', object: 'lexinfo#instrumentalCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form12_mirah', object: '"мирах"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form12_mirah', object: 'lexinfo#plural', predicate: 'lexinfo#number' },
    // {subject: ':mir:form12_mirah', object: 'lexinfo#locativeCase', predicate: 'lexinfo#case' },
    // {subject: ':mir:form13_miru', object: '"миру"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form13_miru', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
    // {subject: ':mir:form14_miru', object: '"миру"@ru', predicate: 'ontolex#writtenRep' },
    // {subject: ':mir:form14_miru', object: 'lexinfo#singular', predicate: 'lexinfo#number' },
]
